To answer the questions, please refer to the name of the dataset at the end of each question.

In [1]:
# Question 1
# Read this file and get its first 8 and last 4 rows and show total number of observations (tips data (excel))
import pandas as pd
df = pd.read_csv('TIPS_data2.csv')
head=df.head(8)
tail=df.tail(4)
head.merge(tail, how='outer')
pd.concat([head, tail])

        Name   Surname  total_bill   tip     sex smoker     day    time  size
0      Adele    Groves       16.99  1.01  Female     No     Sun  Dinner     2
1       Josh    Wilson       10.34  1.66    Male     No     Sun  Dinner     3
2        NaN  Morrison       21.01  3.50    Male     No     Sun  Dinner     3
3     Harvey   Kennedy       23.68  3.31    Male     No     Sun  Dinner     2
4        NaN      Webb       24.59  3.61  Female     No     Sun  Dinner     4
5    Lleyton   Douglas       25.29  4.71    Male     No     Sun  Dinner     4
6        NaN  Crawford        8.77  2.00    Male     No     Sun  Dinner     2
7     Alexis   Vincent       26.88  3.12    Male     No     Sun  Dinner     4
241    Scott       NaN       22.67  2.00    Male    Yes     Sat  Dinner     2
242     Ajay     Munro       17.82  1.75    Male     No     Sat  Dinner     2
243  Tereasa  Duquette       18.78  3.00  Female     No    Thur  Dinner     2
244    Adele    Groves       18.43  2.03  Female     No  Monday  Dinner     3

In [2]:
# Question 2
# What is the most frequent day of given tips? (tips data)
df['day'].value_counts().head(1)

day
Sat    87
Name: count, dtype: int64

In [3]:
# Question 3
# Find number of bills greater than daily average and display them (tips data)
df=pd.read_csv('tips.csv')
pd.set_option('display.max_rows', None)
df.groupby('day')[['total_bill']].mean()

      total_bill
day
Fri    17.151579
Sat    20.441379
Sun    21.410000
Thur   17.682742

In [4]:
# Question 4
# Filter out the customers who's name is longer than the surname (tips data)
df2=pd.read_csv('TIPS_data2.csv')
df2[df2['Name'].str.len() > df2['Surname'].str.len()]

          Name  Surname  total_bill    tip     sex smoker   day    time  size
9    Alexandra   Rahman       14.78   3.23    Male     No   Sun  Dinner     2
10     Claudia     Real       10.27   1.71    Male     No   Sun  Dinner     2
14     Deborah   Wilson       14.83   3.02  Female     No   Sun  Dinner     2
21       Sofia      Cox       20.29   2.75  Female     No   Sat  Dinner     2
24        Luca      Way       19.82   3.18    Male     No   Sat  Dinner     2
25      Rachel    Perry       17.81   2.34    Male     No   Sat  Dinner     4
26     Kenneth   Barton       13.37   2.00    Male     No   Sat  Dinner     2
28      Edward    Cline       21.70   4.30    Male     No   Sat  Dinner     2
29     Chelsea    Lynch       19.65   3.00  Female     No   Sat  Dinner     2
31   Katherine    Kelly       18.35   2.50    Male     No   Sat  Dinner     4
32    Mitchell     Peel       15.06   3.00  Female     No   Sat  Dinner     2
36     Charles    Stork       16.31   2.00    Male     No   Sat  Dinner     3
38     Jasmine     Bage       18.69   2.31    Male     No   Sat  Dinner     3
41     Richard    Felix       17.46   2.54    Male     No   Sun  Dinner     2
42     Melissa    Clark       13.94   3.06    Male     No   Sun  Dinner     2
48      Andrew     Pugh       28.55   2.05    Male     No   Sun  Dinner     3
57     Beverly     Bean       26.41   1.50  Female     No   Sat  Dinner     2
60   Catherine    Davis       20.29   3.21    Male    Yes   Sat  Dinner     2
61       Alice     Dunn       13.81   2.00    Male    Yes   Sat  Dinner     2
70      Samuel    Taber       12.02   1.97    Male     No   Sat  Dinner     2
76      Lilian    Leddy       17.92   3.08    Male    Yes   Sat  Dinner     2
77      Joseph     Best       27.20   4.00    Male     No  Thur   Lunch     4
79     Charlie    Duffy       17.29   2.71    Male     No  Thur   Lunch     2
85     Melissa     Hill       34.83   5.17  Female     No  Thur   Lunch     4
86      Isabel     Dodd       13.03   2.00    Male     No  Thur   Lunch     2
91    Scarlett  Webster       22.49   3.50    Male     No   Fri  Dinner     2
94     Indiana     Rays       22.75   3.25  Female     No   Fri  Dinner     2
100     Andrew    Hagen       11.35   2.50  Female    Yes   Fri  Dinner     2
102    Madison     Hunt       44.30   2.50  Female    Yes   Sat  Dinner     3
103      David     Rizo       22.42   3.48  Female    Yes   Sat  Dinner     2
107    Georgia   Noblet       25.21   4.29    Male    Yes   Sat  Dinner     2
108     Elliot     Kirk       18.24   3.76    Male     No   Sat  Dinner     2
114      Tilly     Dunn       25.71   4.00  Female     No   Sun  Dinner     3
118       Isla      Dow       12.43   1.80  Female     No  Thur   Lunch     2
121  Gabriella    Kelly       13.42   1.68  Female     No  Thur   Lunch     2
122   Victoria  Bradley       14.26   2.50    Male     No  Thur   Lunch     2
128  Lily-rose  Fleming       11.38   2.00  Female     No  Thur   Lunch     2
129     Archer      Ham       22.82   2.18    Male     No  Thur   Lunch     3
132    Michael     Hill       11.17   1.50  Female     No  Thur   Lunch     2
135      Henry     Loch        8.51   1.25  Female     No  Thur   Lunch     2
141     Hayden     Hill       34.30   6.70    Male     No  Thur   Lunch     6
143     Morgan    Green       27.05   5.00  Female     No  Thur   Lunch     6
145   Benjamin  Shelley        8.35   1.50  Female     No  Thur   Lunch     2
146      Clare     Muir       18.64   1.36  Female     No  Thur   Lunch     3
147   Samantha  Walpole       11.87   1.63  Female     No  Thur   Lunch     2
152    Matthew     Read       17.26   2.74    Male     No   Sun  Dinner     3
153  Christine    Dowdy       24.55   2.00    Male     No   Sun  Dinner     4
157     Conall     Shaw       25.00   3.75  Female     No   Sun  Dinner     4
159    Michael     Gunn       16.49   2.00    Male     No   Sun  Dinner     4
163     Daniel     Bell       13.81   2.00    Male     No   Sun  Dinner     2
165     Millar     Kerr       24.52   3.48    Male     No   Sun  Dinner     3
170  Stephanie    Foley       50.81  10.00    Male    Yes   Sat  Dinner     3
174    Alberto   Kovach       16.82   4.00    Male    Yes   Sun  Dinner     2
175    Barbara    Jones       32.90   3.11    Male    Yes   Sun  Dinner     2
182     Bertha    Siler       45.35   3.50    Male    Yes   Sun  Dinner     3
190    Mikayla   Wrench       15.69   1.50    Male    Yes   Sun  Dinner     2
193    Melissa   Talbot       15.48   2.02    Male    Yes  Thur   Lunch     2
197    Patrick   Barber       43.11   5.00  Female    Yes  Thur   Lunch     4
201    Kaitlyn   Nguyen       12.74   2.01  Female    Yes  Thur   Lunch     2
209      Brian     Kerr       12.76   2.23  Female    Yes   Sat  Dinner     2
210     Finlay     Sims       30.06   2.00    Male    Yes   Sat  Dinner     3
214      Larry     Hill       28.17   6.50  Female    Yes   Sat  Dinner     3
220     Esther    Berry       12.16   2.20    Male    Yes   Fri   Lunch     2
221    William   Martin       13.42   3.48  Female    Yes   Fri   Lunch     2
231    Michael    Lucas       15.69   3.00    Male    Yes   Sat  Dinner     3
235     Kaylin     Wood       10.07   1.25    Male     No   Sat  Dinner     2

In [5]:
# Question 5
# Read this text file and bring information only about females who smoke (tips data (text))
df[(df['sex']=='Female') & (df['smoker']=='Yes')]['smoker'].count()
df[(df['sex']=='Female') & (df['smoker']=='Yes')]

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
67           67        3.07  1.00  Female    Yes   Sat  Dinner     1
72           72       26.86  3.14  Female    Yes   Sat  Dinner     2
73           73       25.28  5.00  Female    Yes   Sat  Dinner     2
92           92        5.75  1.00  Female    Yes   Fri  Dinner     2
93           93       16.32  4.30  Female    Yes   Fri  Dinner     2
100         100       11.35  2.50  Female    Yes   Fri  Dinner     2
101         101       15.38  3.00  Female    Yes   Fri  Dinner     2
102         102       44.30  2.50  Female    Yes   Sat  Dinner     3
103         103       22.42  3.48  Female    Yes   Sat  Dinner     2
109         109       14.31  4.00  Female    Yes   Sat  Dinner     2
164         164       17.51  3.00  Female    Yes   Sun  Dinner     2
168         168       10.59  1.61  Female    Yes   Sat  Dinner     2
169         169       10.63  2.00  Female    Yes   Sat  Dinner     2
178         178        9.60  4.00  Female    Yes   Sun  Dinner     2
186         186       20.90  3.50  Female    Yes   Sun  Dinner     3
188         188       18.15  3.50  Female    Yes   Sun  Dinner     3
191         191       19.81  4.19  Female    Yes  Thur   Lunch     2
197         197       43.11  5.00  Female    Yes  Thur   Lunch     4
198         198       13.00  2.00  Female    Yes  Thur   Lunch     2
201         201       12.74  2.01  Female    Yes  Thur   Lunch     2
202         202       13.00  2.00  Female    Yes  Thur   Lunch     2
203         203       16.40  2.50  Female    Yes  Thur   Lunch     2
205         205       16.47  3.23  Female    Yes  Thur   Lunch     3
209         209       12.76  2.23  Female    Yes   Sat  Dinner     2
213         213       13.27  2.50  Female    Yes   Sat  Dinner     2
214         214       28.17  6.50  Female    Yes   Sat  Dinner     3
215         215       12.90  1.10  Female    Yes   Sat  Dinner     2
219         219       30.14  3.09  Female    Yes   Sat  Dinner     4
221         221       13.42  3.48  Female    Yes   Fri   Lunch     2
225         225       16.27  2.50  Female    Yes   Fri   Lunch     2
226         226       10.09  2.00  Female    Yes   Fri   Lunch     2
229         229       22.12  2.88  Female    Yes   Sat  Dinner     2
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2

In [6]:
# Question 6
# Read this excel file and bring only the records containing at least one null value (tips data)
df=pd.read_csv('TIPS_data2.csv')
df.isna().any()
df[df.isnull().any(axis=1)]

,Name,Surname,total_bill,tip,sex,smoker,day,time,size
2,NaN,Morrison,21.01,3.50,Male,No,Sun,Dinner,3
4,NaN,Webb,24.59,3.61,Female,No,Sun,Dinner,4
6,NaN,Crawford,8.77,2.00,Male,No,Sun,Dinner,2
8,NaN,Pratt,15.04,1.96,Male,No,Sun,Dinner,2
16,William,NaN,10.33,1.67,Female,No,Sun,Dinner,3
19,NaN,Findlay,20.65,3.35,Male,No,Sat,Dinner,3
33,NaN,NaN,20.69,2.45,Female,No,Sat,Dinner,4
49,NaN,NaN,18.04,3.00,Male,No,Sun,Dinner,2
72,NaN,Boag,26.86,3.14,Female,Yes,Sat,Dinner,2
88,Michael,NaN,24.71,5.85,Male,No,Thur,Lunch,2
110,Hugh,NaN,14.00,3.00,Male,No,Sat,Dinner,2
117,NaN,Jones,10.65,1.50,Female,No,Thur,Lunch,2
137,NaN,Gonzalez,14.15,2.00,Female,No,Thur,Lunch,2
155,Sebastian,NaN,29.85,5.14,Female,No,Sun,Dinner,5
166,Keeva,NaN,20.76,2.24,Male,No,Sun,Dinner,2
171,NaN,Collits,15.81,3.16,Male,Yes,Sat,Dinner,2
178,Roger,NaN,9.60,4.00,Female,Yes,Sun,Dinner,2
181,NaN,Grimm,23.33,5.65,Male,Yes,Sun,Dinner,2
185,Molly,NaN,20.69,5.00,Male,No,Sun,Dinner,5
191,NaN,Bentley,19.81,4.19,Female,Yes,Thur,Lunch,2
192,NaN,Barry,28.44,2.56,Male,Yes,Thur,Lunch,2
195,Alasdair,NaN,7.56,1.44,Male,No,Thur,Lunch,2
198,NaN,Chamberlain,13.00,2.00,Female,Yes,Thur,Lunch,2
202,Henry,NaN,13.00,2.00,Female,Yes,Thur,Lunch,2
213,NaN,Stanford,13.27,2.50,Female,Yes,Sat,Dinner,2
217,NaN,Jones,11.59,1.50,Male,Yes,Sat,Dinner,2
219,NaN,NaN,30.14,3.09,Female,Yes,Sat,Dinner,4
227,NaN,Smart,20.45,3.00,Male,No,Sat,Dinner,4
229,Rocky,NaN,22.12,2.88,Female,Yes,Sat,Dinner,2
238,NaN,Wilson,35.83,4.67,Female,No,Sat,Dinner,3
239,NaN,Mitchell,29.03,5.92,Male,No,Sat,Dinner,3
240,NaN,Teece,27.18,2.00,Female,Yes,Sat,Dinner,2
241,Scott,NaN,22.67,2.00,Male,Yes,Sat,Dinner,2

In [7]:
# Question 7
# How many people have the same name and surname? (tips data)
df=pd.read_csv('TIPS_data2.csv')
df[df['Name']==df['Surname']]

df_new=df.groupby(['Name','Surname']).size().reset_index(name='count')
df_new[df_new['count']>1]

    Name Surname  count
3  Adele  Groves      2

In [9]:
# Question 8
# Do females tip more than males? Which measures do you use for this problem and why? (tips data)
df=pd.read_csv('tips.csv')
df.groupby('sex')['tip'].sum()

sex
Female    246.51
Male      485.07
Name: tip, dtype: float64